<?php 
 /**
 * Market Academy SAS 
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * It is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright  Copyright (c) Market Academy SAS. (http://www.market-academy.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div id="maHelp">
	<iframe src="<?php echo Mage::getModel('mavideohelp/service')->iframeUrl() ?>" name="marketVideoPanel" id="marketVideoPanel" frameborder="0" style="width:100%;height:100%;" allowFullscreen></iframe>
</div>
<script type="text/javascript">
	var IDUSERSADMIN 	= <?php echo "'".$this->userId()."'"; ?>;
	var ADDUSERURL 		= <?php echo "'".Mage::helper('adminhtml')->getUrl('mavideohelp/users/adduser')."'"; ?>;
</script>
<script type="text/javaScript" src="https://tuto.market-academy.com/js/iframe.js"></script>
