<?php 
 /**
 * Market Academy SAS 
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * It is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright  Copyright (c) Market Academy SAS. (http://www.market-academy.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
	$key = Mage::getModel('mavideohelp/users')->getKey();
?>
<?php if ($key): ?>
	<iframe src="<?php echo Mage::getModel('mavideohelp/service')->getTableFrameUrl() ?>" frameborder="0" id="tableIframeContainer" ></iframe>
	<script language="javascript" type="text/javascript">
		function receiveSize(e){
	    	if(e.origin === "https://tuto.market-academy.com"){
	        	var newHeight = e.data+20 ;
	        	$("tableIframeContainer").setStyle({height:newHeight+"px"})
	        }
	    }
		window.addEventListener("message", receiveSize, false);
	</script>
	<script type="text/javascript">
		Event.observe(window, 'load', function() {
			$("imgBtnOpen").hide();
		});	
	</script>
<?php else: ?>
	<h2>Pour accéder a cette page connectez vous depuis le panneau de droite</h2>
<?php endif ?>

<?php 
	$isOpen	= Mage::getStoreConfig('mavideohelp_options/section_one/mavideohelp_alwaysOpen',$store);
	if ($isOpen) {
?>
		<script type="text/javascript">
			Event.observe(window, 'load', function() {
				var wrapper = document.getElementsByClassName("wrapper")[0];
				var MA 		= document.getElementById('maHelp');
				document.getElementById('openTutosVideo').toggleClassName('panelOpen');
				wrapper.toggleClassName('maVideosTrue');
				MA.toggleClassName('actif');
			});
		</script>
<?php
	}
?>